name: Get changed packages
description:
  Compares your git branch to its base, list changed files and output related
  packages
author: Cedric Nicoloso (cedric.nicoloso@gmail.com)

branding:
  icon: package
  color: blue

outputs:
  changed_packages:
    description: List of changed packages, one package per line
  changed_packages_one_line:
    description: List of changed packages, separated by one space

runs:
  using: node24
  main: dist/index.js
